Repository SOPT-all/36-STUDY-WEB-PERFORM-OPTIMIZATION-STUDY, pull requests merged in 2025-05, with the labels that each got.

#1 [Week1] 권동희 - 블로그 최적화
  .DS_Store
  hamxxn/week1/docs/lecture-1.md
Labels: 1주차, 동희

#2 [Week1] 윤소은 - 블로그 최적화
  soeun/week1/docs/blog-service-1.md
  soeun/week1/docs/img/1200.png
  soeun/week1/docs/img/240.png
  soeun/week1/docs/img/img-cdn.png
  soeun/week1/docs/img/lighthouse.png
  soeun/week1/docs/img/lighthouse2.png
  soeun/week1/playground/lecture-1/.gitignore
  soeun/week1/playground/lecture-1/README.md
  soeun/week1/playground/lecture-1/package-lock.json
  soeun/week1/playground/lecture-1/package.json
  soeun/week1/playground/lecture-1/public/favicon.ico
  soeun/week1/playground/lecture-1/public/index.html
  soeun/week1/playground/lecture-1/public/manifest.json
  soeun/week1/playground/lecture-1/public/robots.txt
  soeun/week1/playground/lecture-1/server/config.json
  soeun/week1/playground/lecture-1/server/database.json
  soeun/week1/playground/lecture-1/src/App.css
  soeun/week1/playground/lecture-1/src/App.js
  soeun/week1/playground/lecture-1/src/components/Article/index.css
  soeun/week1/playground/lecture-1/src/components/Article/index.js
  soeun/week1/playground/lecture-1/src/components/ArticleList/index.css
  soeun/week1/playground/lecture-1/src/components/ArticleList/index.js
  soeun/week1/playground/lecture-1/src/components/Footer/index.css
  soeun/week1/playground/lecture-1/src/components/Footer/index.js
  soeun/week1/playground/lecture-1/src/components/Header/index.css
  soeun/week1/playground/lecture-1/src/components/Header/index.js
  soeun/week1/playground/lecture-1/src/components/markdowns/CodeBlock.js
  soeun/week1/playground/lecture-1/src/index.css
  soeun/week1/playground/lecture-1/src/index.js
  soeun/week1/playground/lecture-1/src/pages/ListPage/index.css
  soeun/week1/playground/lecture-1/src/pages/ListPage/index.js
  soeun/week1/playground/lecture-1/src/pages/ViewPage/index.css
  soeun/week1/playground/lecture-1/src/pages/ViewPage/index.js
  soeun/week1/playground/lecture-1/src/templates/BasicTemplates.js
  soeun/week1/playground/lecture-1/yarn.lock
Labels: 1주차, 소은

#4 [Week1] 박희선 - 블로그 이미지 최적화
  heesun/docs/image-1.png
  heesun/docs/image-2.png
  heesun/docs/image-3.png
  heesun/docs/image.png
  heesun/docs/블로그_서비스_최적화.md
Labels: 1주차, 희선

#7 [Week2] 윤소은 - 블로그 서비스 최적화, 올림픽 통계 서비스 최적화
  soeun/week2/docs/blog-service-2.md
  soeun/week2/docs/olympic-service.md
Labels: 2주차, 소은

#9 [Week2] 박희선 - 블로그 서비스 최적화, 올림픽 통계 서비스 최적화
  heesun/week2/docs/블로그서비스(2).md
  heesun/week2/docs/올림픽최적화.md
Labels: 2주차, 희선

#10 [Week2] 이재림 - 블로그 서비스 최적화, 올림픽 통계 서비스 최적화
  jaelim/week2/docs/blog-service-2.md
  jaelim/week2/docs/olympic-service.md
Labels: 2주차, 재림

#11 [Week2] 엄경호 - 블로그 서비스 최적화, 올림픽 통계 서비스 최적화
  kyoungho/week2/docs/blogService-2.md
  kyoungho/week2/docs/olympicStatistics.md
  kyoungho/week2/playground/lecture-2/src/App.js
  kyoungho/week2/playground/lecture-2/src/components/Bar.js
  kyoungho/week2/playground/lecture-2/src/components/ImageModal.js
Labels: 2주차, 경호

#15 [Week3] 이재림 - 홈페이지 최적화
  jaelim/week3/docs/lecture-3.md
Labels: 3주차, 재림

#16 [Week3] 박희선 - 홈페이지 최적화
  heesun/week3/docs/이미지.md
Labels: 3주차, 희선
